### ISSUE TITLE
Add an updatecli manifest to keep track of hashicorp-tools version

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/aws#120]
https://github.com/jenkins-infra/aws/blob/9cbffe8ada22773c1a63425adf9643cb0b1da680/Jenkinsfile_k8s#L18-L20

Follow-up of https://github.com/jenkins-infra/aws/pull/119

Add an updatecli manifest to track the hashicorp image version used within jenkinsfile for updatecli run

- [x] aws
- [x] datadog
- [x] digitalocean

**Comment by dduportal** [comment]
yup, thanks for the issue!

Assigned to Stephane as he's going to take care of it tomorrow :)

**Comment by smerle33** [comment]
Add an updatecli manifest to track the hashicorp image version used within jenkinsfile for updatecli run

- [ ] aws
- [ ] datadog
- [ ] digitalocean
